import Head from 'next/head';
import Image from 'next/image';
import pineapple from '../public/pineapple.png';



export default function Home() {
  return (
    <div>
      <Head>
        <title>Pineapple Street Market</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
<link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin/>
<link href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet"/>
      </Head>
      <main>
        
        <div  style={{ backgroundColor: '#ff9d0b' }} >
         <section> <div><nav style={{ backgroundColor: '#fdbf39' }} className='flex sticky top-0 shadow-lg z-  py-1'>
        <h1 className=' pl-3 pr-20 leading-4 font-extrabold'>Pineapple<br />Street<br />Market</h1>
        <ul className='flex gap-10 items-center'>
          <a href='#home' className='hover:text-white'><li>Home</li></a>
          <a href='#location'className='hover:text-white' ><li>Location</li></a>
          <a href='#' className='hover:text-white'><li>About Us</li></a>
          <a href='#' className='hover:text-white'><li>Contact Us</li></a>
          
        </ul>
         </nav></div>
         </section>
         <section id='home' className='pl-80 flex gap-1'  >
          <div><h1 className=' text-6xl pl-30 py-20 ' ><span className='font-extrabold'>Delicious</span><br />Pineapple</h1>
          <p className='text-xl font-bold'>taking speacializing to a <br /> whole new level.</p>
          <button style={{ backgroundColor: '#FF7406' }} className=' text-white font-bold 
          py-2 my-3 px-3 hover:shadow-xl rounded-2xl'>Learn More</button>
          <p className='ml-10 font-bold '>or</p>
          <button style={{ backgroundColor: '#FF7406' }} className='  text-white font-bold py-2 my-3 px-3 hover:shadow-xl rounded-2xl'>Order Now</button>
          </div>
          <div className=' relative bottom-28 left-30'><Image src={pineapple} width={500} height={800} /></div>
         </section>
         <section> 
         <div> <h1 className='text-6xl pl-30 py-10 pl-40' id='location'>Location</h1>
          <p className='pb-10 pl-40 font-medium text-lg'>Find Our Location in the Map down below.</p></div>
          <div>
          <iframe  src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3024.8844446326284!2d-73.99648648505757!3d40.69854254637649!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89c25a37f4dbf3ef%3A0xac15aae3bea310d8!2sPineapple%20St%2C%20Brooklyn%2C%20NY%2011201%2C%20USA!5e0!3m2!1sen!2stt!4v1674104814272!5m2!1sen!2stt" width="1000" height="350" style={{border:"0"}}  loading="lazy" referrerPolicy="no-referrer-when-downgrade" className='mx-40 rounded-md hover:ease-in-out duration-300 '></iframe>
          </div>
          </section>  
          <section>
            <h1 className='text-6xl pl-30 py-20 pl-40'>About Us</h1>
           <div style={{ backgroundColor: '#fdbf39' }} className='mx-40 pt-20'> <p className='max-w-2xl mx-auto py-2 text-lg '>Welcome to Pineapple Street Market, the premier destination for pineapple lovers! We are a specialty store that is passionate about providing the freshest and most delicious pineapples to our customers.</p>
            <p className='max-w-2xl mx-auto py-2 text-lg '>At Pineapple Street Market, we believe that the sweet and tangy taste of pineapples should be enjoyed by everyone. That's why we source our pineapples from the finest growers in the world to ensure that our customers receive the highest quality fruit.</p>
            <p className='max-w-2xl mx-auto py-2 text-lg '>Our team of experts is dedicated to hand-selecting only the best pineapples for our store. We take pride in offering a wide variety of pineapples, from the classic golden pineapples to the more exotic varieties such as red and mini pineapples.</p>
            <p className='max-w-2xl mx-auto py-2 text-lg  '>We understand that everyone has different tastes and preferences, which is why we offer a range of pineapple-based products, such as freshly squeezed pineapple juice and pineapple smoothies. Our store also carries a selection of pineapple-themed merchandise, from kitchen accessories to clothing and decor.</p>
            <p className='max-w-2xl mx-auto py-2 text-lg '>We are committed to providing our customers with exceptional service and a memorable shopping experience. Our knowledgeable staff is always available to answer any questions and to help you select the perfect pineapple for your needs.</p>
            <p className='max-w-2xl mx-auto py-2 text-lg '>At Pineapple Street Market, we are more than just a store - we are a community of pineapple enthusiasts. Join us in celebrating this delicious fruit by stopping by our store and experiencing the sweet taste of the tropics.</p></div>
          </section>
        </div>
      </main>
    </div>
  );
}
